name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: npm install

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Package.json
      uses: actions/setup-package.json
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm start
